apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: linuxserver/plex
          env:
            - name: PGID
              value: "{{GROUP_ID}}"
            - name: PUID
              value: "{{USER_ID}}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: storage
              mountPath: "{{STORAGE_DIR}}"
          livenessProbe:
            httpGet:
              path: /web
              port: 32400
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /web
              port: 32400
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: config
          hostPath:
            path: "{{CONFIG_DIR}}/plex"
        - name: storage
          hostPath:
            path: "{{STORAGE_DIR}}"
